### ISSUE TITLE
Filter Diffusion DB

### ISSUE THREAD

**Issue by king159** [CroitoruAlin/Reverse-Stable-Diffusion#1]
Thank you for your nice work!

As mentioned on page 7, you filtered the DiffusionDB and obtained **730,000** clean pairs. Would you mind sharing the filter code?

**Comment by CroitoruAlin** [comment]
Hi,
Sure, here is the script:

`
def is_english_only(string):
    for s in string:
        cat = unicodedata.category(s)         
        if not cat in ['Ll', 'Lu', 'Nd', 'Po', 'Pd', 'Zs']:
            return False
    return True

df = pd.read_parquet('metadata.parquet', columns=['image_name', 'prompt', 'width', 'height'])

df['prompt'] = df['prompt'].str.strip()
df = df[df['prompt'].map(lambda x: len(x.split())) >= 1]
df = df[~df['prompt'].str.contains('^(?:\s*|NULL|null|NaN)$', na=True)]
df = df[df['prompt'].apply(is_english_only)]
df['head'] = df['prompt'].str[:50]
df['tail'] = df['prompt'].str[-50:]
df.drop_duplicates(subset='head', inplace=True)
df.drop_duplicates(subset='tail', inplace=True)
df.reset_index(drop=True, inplace=True)`
